apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: javamelody-collector-url
  namespace: sample
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: javamelody-collector-url
    creationPolicy: Owner
    template:
      data:
        JAVAMELODY_COLLECTOR_URL: "http://{{ .auth }}@javamelody-collector.monitoring.svc.cluster.local:8080"
  data:
    - secretKey: auth
      remoteRef:
        key: eks-lab/credentials
        property: javamelody-auth
