apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: javamelody-auth
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: javamelody-auth
    creationPolicy: Owner
    template:
      data:
        JAVAMELODY_AUTHORIZED_USERS: "{{ .auth }}"
  data:
    - secretKey: auth
      remoteRef:
        key: eks-lab/credentials
        property: javamelody-auth
